services:
  - type: web
    name: EcoVoice-Analyzer
    env: python
    rootDir: backend
    plan: free
    buildCommand: >
      pip install -r requirements.txt &&
      python -m spacy download en_core_web_md
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: COHERE_API_KEY
        sync: false  # Set the value in the Render dashboard
      - key: DATABASE_URL
        sync: false
