services:
  - type: web
    name: pollution-analyzer-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: COHERE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: false